feat: fungerende monitorkode for naisjob/job
nais/naiserator pull request #321
Opened 2022-03-10 08:10 UTC by Kyrremann

Co-authored-by: Kent Daleng <kent.daleng@nav.no>

2022-03-14 18:32 UTC, Kyrremann commented
Mangler bare å få merget inn https://github.com/nais/liberator/pull/48 så er denne klar

2022-03-14 18:33 UTC, Kyrremann commented
Ble to oppgaver i denne egentlig. Ble også rettet opp noen synkroniseringsproblemer som oppstod etter at finalizer ble lagt til. For å unngå at for mange `update` ble kjørt.

2022-03-15 12:34 UTC, ambientsound requested changes

2022-03-16 14:20 UTC, chinatsu commented
krever en sjekk i et testcluster for å verifisere at deployments av `Application`, og `Naisjob` med og uten schedule blir håndtert som forventet. pr. i dag er det ikke lett å teste med integrasjonstester dessverre

2022-03-22 09:40 UTC, merged